Repository CMPUT301F20T12/BookFace, pull requests merged in 2020-11, with the labels that each got.

#48 pzafra/search front end
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/bookface/BookList.java
  app/src/main/java/com/example/bookface/SearchActivity.java
  app/src/main/res/layout/activity_search.xml
  app/src/main/res/layout/book_list.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: US 03.01.01, US 03.02.01

#60 Search Functionality
  app/src/main/java/com/example/bookface/BookList.java
  app/src/main/java/com/example/bookface/MyBooks.java
  app/src/main/java/com/example/bookface/SearchActivity.java
  app/src/main/java/com/example/bookface/UserProfileActivity.java
  app/src/main/res/layout/activity_search.xml
  app/src/main/res/layout/book.xml
  app/src/main/res/layout/my_books.xml
Labels: NOT READY

#53 My books
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/bookface/AddEditBookActivity.java
  app/src/main/java/com/example/bookface/BookDescription.java
  app/src/main/java/com/example/bookface/MyBooks.java
  app/src/main/java/com/example/bookface/Notification.java
  app/src/main/res/layout/activity_book_description.xml
  app/src/main/res/layout/my_books.xml
Labels: DONE

#66 Send Request from Search
  app/src/main/java/com/example/bookface/Book.java
  app/src/main/java/com/example/bookface/BookDescription.java
  app/src/main/java/com/example/bookface/SearchActivity.java
  app/src/main/java/com/example/bookface/SendRequestDialog.java
Labels: NOT READY

#70 Clean code kanishk
  app/src/main/java/com/example/bookface/AddEditBookActivity.java
  app/src/main/java/com/example/bookface/Book.java
  app/src/main/java/com/example/bookface/BookDescription.java
  app/src/main/java/com/example/bookface/BookList.java
  app/src/main/java/com/example/bookface/CaptureAct.java
  app/src/main/java/com/example/bookface/EditProfileFragment.java
  app/src/main/java/com/example/bookface/MainActivity.java
  app/src/main/java/com/example/bookface/MyBooks.java
  app/src/main/java/com/example/bookface/MyRequestsActivity.java
  app/src/main/java/com/example/bookface/Notification.java
  app/src/main/java/com/example/bookface/RecyclerViewAdapter.java
  app/src/main/java/com/example/bookface/Request.java
  app/src/main/java/com/example/bookface/RequestList.java
  app/src/main/java/com/example/bookface/Scan.java
  app/src/main/java/com/example/bookface/SearchActivity.java
  app/src/main/java/com/example/bookface/SignupActivity.java
  app/src/main/java/com/example/bookface/User.java
  app/src/main/java/com/example/bookface/UserProfileActivity.java
Labels: question
